
#include"keywords.h"

const char* tlas_kw[TLAS_KW_COUNT] = {
	[TLAS_KW_REG_A] = "a",
	[TLAS_KW_REG_D] = "d",
	[TLAS_KW_REG_F] = "f",
	[TLAS_KW_REG_I] = "i",
	[TLAS_KW_REG_K] = "k",
	[TLAS_KW_REG_O] = "o",
	[TLAS_KW_REG_P] = "p",
	[TLAS_KW_REG_S] = "s",

	[TLAS_KW_AT_A] = "*a",
	[TLAS_KW_AT_D] = "*d",
	[TLAS_KW_AT_K] = "*k",
	[TLAS_KW_AT_P] = "*p",

	[TLAS_KW_AT_AT_A] = "**a",
	[TLAS_KW_AT_AT_D] = "**d",
	[TLAS_KW_AT_AT_K] = "**k",
	[TLAS_KW_AT_AT_P] = "**p",

	[TLAS_KW_FLAG_B] = "fb",
	[TLAS_KW_FLAG_C] = "fc",
	[TLAS_KW_FLAG_I] = "fi",
	[TLAS_KW_FLAG_N] = "fn",
	[TLAS_KW_FLAG_O] = "fo",
	[TLAS_KW_FLAG_S] = "fs",
	[TLAS_KW_FLAG_U] = "fu",
	[TLAS_KW_FLAG_Z] = "fz",

	[TLAS_KW_ADD] = "add",
	[TLAS_KW_ADD_CARRY] = "addc",
	[TLAS_KW_BITWISE_AND] = "and",
	[TLAS_KW_BITWISE_NOR] = "nor",
	[TLAS_KW_BITWISE_NOT] = "not",
	[TLAS_KW_BITWISE_OR] = "or",
	[TLAS_KW_BITWISE_XOR] = "xor",
	[TLAS_KW_BREAK] = "brk",
	[TLAS_KW_CALL] = "call",
	[TLAS_KW_COMPARE] = "cmp",
	[TLAS_KW_DECREMENT] = "dec",
	[TLAS_KW_HALT] = "hlt",
	[TLAS_KW_IN] = "in",
	[TLAS_KW_INCREMENT] = "inc",
	[TLAS_KW_INTRET] = "rti",
	[TLAS_KW_JUMP] = "jmp",
	[TLAS_KW_JUMP_IF] = "jif",
	[TLAS_KW_LOOP] = "loop",
	[TLAS_KW_MOVE] = "mov",
	[TLAS_KW_NEGATIVE] = "neg",
	[TLAS_KW_NOPE] = "nop",
	[TLAS_KW_OUT] = "out",
	[TLAS_KW_PEEK] = "peek",
	[TLAS_KW_POP] = "pop",
	[TLAS_KW_POP_ALL] = "popa",
	[TLAS_KW_PUSH] = "push",
	[TLAS_KW_PUSH_ALL] = "psha",
	[TLAS_KW_SET_FLAG] = "setf",
	[TLAS_KW_SHIFT_LEFT] = "shl",
	[TLAS_KW_SHIFT_LEFT_CARRY] = "shlc",
	[TLAS_KW_SHIFT_RIGHT] = "shr",
	[TLAS_KW_SHIFT_RIGHT_CARRY] = "shrc",
	[TLAS_KW_SUB] = "sub",
	[TLAS_KW_SUB_CARRY] = "subc",
	[TLAS_KW_SWAP] = "swp",
	[TLAS_KW_TEST] = "test",
	
	[TLAS_KW_DEF_BYTES] = "db",
	[TLAS_KW_RES_BYTES] = "rb",
	[TLAS_KW_INCLUDE_BIN] = "incbin",
	[TLAS_KW_INCLUDE_ASM] = "incasm",
	[TLAS_KW_MACRO_BEGIN] = "def",
	[TLAS_KW_MACRO_END] = "end",
	[TLAS_KW_MACRO_REMOVE] = "undef",

	[TLAS_KW_TRUE] = "true",
	[TLAS_KW_FALSE] = "false",
	[TLAS_KW_ABS_POS] = "$",
	[TLAS_KW_REL_POS] = "$$",

	[TLAS_KW_OP_ADD] = "+",
	[TLAS_KW_OP_AND] = "&",
	[TLAS_KW_OP_DIV] = "/",
	[TLAS_KW_OP_MOD] = "%",
	[TLAS_KW_OP_MUL] = "*",
	[TLAS_KW_OP_NOT] = "~",
	[TLAS_KW_OP_OR] = "|",
	[TLAS_KW_OP_SHIFTL] = "<<",
	[TLAS_KW_OP_SHIFTR] = ">>",
	[TLAS_KW_OP_SUB] = "-",
	[TLAS_KW_OP_XOR] = "^",
};